# Generated by Django 5.2 on 2026-01-18 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("visible_to_company_ids", models.JSONField(default=list)),
                ("related_entity_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_by_user_ids", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
